### ISSUE TITLE
failed svc_init seems stuck

### ISSUE THREAD

**Issue by ahemon** [fastflow/fastflow#16]
Im trying to play around with the library on Ubuntu with CLang 6.0.1 targeting c++17. I use the fully-c++11 branch.

Im creating a ff_node with the following svc_init:
```
int svc_init() {
        console->info("Init Readile: {}", file_path);
        try {
            file_reader = make_unique<io::LineReader>(file_path);
        } catch(const io::error::can_not_open_file msg) {
            msg.what();
            console->error(fmt::format("Error: {}",msg.error_message_buffer));
            return -1;
        }
        return 0;
    }
```
I add the stage to a ff_Pipe:
```ff_Pipe<Event> pipe(make_unique<ReadFile>("/tmp/access.log2"));```
and run the ff_Pipe:
```if (pipe.run_and_wait_end() < 0) error("running pipe");```

If the svc_init fails and return -1, I would expect the pipeline to end and print the error, however it just hangs forever after printing:
`ERROR: ff_thread, svc_init failed, thread exit!!!`

Is this behavior expected ?

Compiler:
```clang++ --version
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang_6.0.1/bin

**Comment by massimotorquati** [comment]
Thanks for reporting the issue. Currently, if the svc_init method fails, only the thread running it is terminated. Depending on how the application is structured this may cause that the pipeline gets stuck. 
The workaround in your test is to initialize the LineReader in the constructor of the node and not in the svc_init.
