### ISSUE TITLE
ambigue make_unique usage

### ISSUE THREAD

**Issue by droccom** [fastflow/fastflow#7]
https://github.com/fastflow/fastflow/blob/9eabf3a7ac72116ebbaaf40e8c147ce0b9474e3d/tests/test_nodeselector.cpp#L74

ff::make_unique() working, std::make_unique() *not* working

**Comment by jdgarciauc3m** [comment]
What does it mean "not working"?

**Comment by droccom** [comment]
Sorry, I made wrong assumptions about my compilation environment.
The actual issue is minor: if `std::make_unique` is defined, then the compilation fails due to resolution ambiguity. Then it can be solved by just forcing the usage of `ff::make_unique` (that is already rewritten as `std::make_unique` if defined).

**Comment by droccom** [comment]
fixed by 368e5afdea8fa10c360a266ac6bb3ef13350028f

**Comment by jdgarciauc3m** [comment]
I would **very strongly** recommend that you do not use using namespace directives at global scope as you are doing in line 39. That is really risky in some situations.

**Comment by droccom** [comment]
Thank you!
I am fixing it in test_nodeselector.cpp, then I'll create an issue for fixing it everywhere else.
